apiVersion: v1
kind: Template
labels:
  version: "1.0"
  group: infrastructure
metadata:
  name: kong-plugin-basicauth
  annotations:
    description: Plugins Template for Kong
    tags: controller,kong,plugin
    version: "1.0"
objects:

- apiVersion: configuration.konghq.com/v1
  kind: KongConsumer
  metadata:
    name: consumer-basicauth
    annotations:
      kubernetes.io/ingress.class: ${ingress_class}
    labels:
      kong-common: true
  username: consumer-basicauth

- apiVersion: configuration.konghq.com/v1
  kind: KongCredential
  metadata:
    name: credential-basicauth
    annotations:
      kubernetes.io/ingress.class: ${ingress_class}
    labels:
      kong-common: true
  consumerRef: consumer-basicauth
  type: basic-auth
  config:
    username: ${username}
    password: ${password}

- apiVersion: configuration.konghq.com/v1
  kind: KongPlugin
  metadata:
    name: plugin-common-basicauth
    annotations:
      kubernetes.io/ingress.class: ${ingress_class}
    labels:
      kong-common: true
  config:
    hide_credentials: true
  plugin: basic-auth

parameters:
- name: ingress_class
  displayName: Ingress Class
  value: "kong"
  required: true
- name: username
  displayName: Username
  required: true
- name: password
  displayName: Password
  required: true
