apiVersion: v1
kind: Template
labels:
  version: "1.0"
  group: infrastructure
metadata:
  name: kong-plugin-jwt
  annotations:
    description: Plugins Template for Kong
    tags: controller,kong,plugin
    version: "1.0"
objects:

- apiVersion: configuration.konghq.com/v1
  kind: KongConsumer
  metadata:
    name: consumer-jwt
    annotations:
      kubernetes.io/ingress.class: ${ingress_class}
    labels:
      kong-common: true
  username: consumer-jwt


- apiVersion: configuration.konghq.com/v1
  kind: KongCredential
  metadata:
    name: credential-jwt
    annotations:
      kubernetes.io/ingress.class: ${ingress_class}
    labels:
      kong-common: true
  consumerRef: consumer-jwt
  type: jwt
  config:
    key: ${key_claim_value}
    algorithm: RS256
    rsa_public_key: "-----BEGIN PUBLIC KEY-----\n${rsa_public_key}\n-----END PUBLIC KEY-----"


- apiVersion: configuration.konghq.com/v1
  kind: KongPlugin
  metadata:
    name: plugin-common-jwt
    annotations:
      kubernetes.io/ingress.class: ${ingress_class}
    labels:
      kong-common: true
  config:
    claims_to_verify:
      - exp
    header_names:
      - Authorization
    key_claim_name: ${key_claim_name}
    uri_param_names:
      - jwt
      - access_token
  plugin: jwt

parameters:
- name: ingress_class
  displayName: Ingress Class
  value: "kong"
  required: true
- name: key_claim_name
  displayName: JWT Key Claim Name
  required: true
- name: key_claim_value
  displayName: JWT Key Claim Value
  required: true
- name: rsa_public_key
  displayName: JWT RSA Public Key
  required: true
