apiVersion: v1
kind: Template
labels:
  version: "1.0"
  group: infrastructure
metadata:
  annotations:
    description: Kong Ingress Controller - installing Project with policy
    tags: controller,kong
    version: "1.0"
  name: kong-project-template
objects:


- apiVersion: v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${NAMESPACE_DESC}
      openshift.io/display-name: ${NAMESPACE_DISPLAY}
      openshift.io/sa.scc.mcs: s0:c13,c7
      openshift.io/sa.scc.supplemental-groups: 0/10000
      openshift.io/sa.scc.uid-range: 0/10000
    name: ${NAMESPACE}


parameters:
- name: NAMESPACE
  displayName: Kong Namespace
  description: Kong Installation Namespace
  required: true
- name: NAMESPACE_DISPLAY
  displayName: Kong Namespace
  description: Kong Installation Namespace
  required: false
  value: ""
- name: NAMESPACE_DESC
  displayName: Kong Namespace Description
  description: Kong Installation Namespace Description
  required: false
  value: ""
