apiVersion: v1
kind: Template
labels:
  version: "1.0"
  group: infrastructure
metadata:
  annotations:
    description: Kong Ingress Controller - roles and policy
    tags: controller,kong
    version: 1.0
  name: kong-account-template
objects:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: kong-serviceaccount
    labels:
      app: ingress-kong


- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: kong-ingress-clusterrole-nisa-binding
    labels:
      app: ingress-kong
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kong-ingress-clusterrole
  subjects:
  - kind: ServiceAccount
    name: kong-serviceaccount
    namespace: ${NAMESPACE}


- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: kong-ingress-clusterrole-default-binding
    labels:
      app: ingress-kong
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kong-ingress-clusterrole
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: ${NAMESPACE}


parameters:
- name: NAMESPACE
  displayName: Kong Namespace
  description: Kong Installation Namespace
  required: true
