apiVersion: v1
kind: Template
labels:
  version: "1.0"
  group: infrastructure
metadata:
  annotations:
    description: Kong Ingress Controller - CustomResourceDefinition objects and ClusterRole objects
    tags: controller,kong
    version: "1.0"
  name: kong-cluster-template
objects:


- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: kongconsumers.configuration.konghq.com
    labels:
      config: ingress-kong
  spec:
    additionalPrinterColumns:
    - JSONPath: .username
      description: Username of a Kong Consumer
      name: Username
      type: string
    - JSONPath: .metadata.creationTimestamp
      description: Age
      name: Age
      type: date
    group: configuration.konghq.com
    names:
      kind: KongConsumer
      plural: kongconsumers
      shortNames:
      - kc
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          credentials:
            items:
              type: string
            type: array
          custom_id:
            type: string
          username:
            type: string
    version: v1


- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: kongcredentials.configuration.konghq.com
    labels:
      config: ingress-kong
  spec:
    additionalPrinterColumns:
    - JSONPath: .type
      description: Type of credential
      name: Credential-type
      type: string
    - JSONPath: .metadata.creationTimestamp
      description: Age
      name: Age
      type: date
    - JSONPath: .consumerRef
      description: Owner of the credential
      name: Consumer-Ref
      type: string
    group: configuration.konghq.com
    names:
      kind: KongCredential
      plural: kongcredentials
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          consumerRef:
            type: string
          type:
            type: string
        required:
        - consumerRef
        - type
    version: v1


- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: kongingresses.configuration.konghq.com
    labels:
      config: ingress-kong
  spec:
    group: configuration.konghq.com
    names:
      kind: KongIngress
      plural: kongingresses
      shortNames:
      - ki
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          proxy:
            properties:
              connect_timeout:
                minimum: 0
                type: integer
              path:
                pattern: ^/.*$
                type: string
              protocol:
                enum:
                - http
                - https
                - grpc
                - grpcs
                type: string
              read_timeout:
                minimum: 0
                type: integer
              retries:
                minimum: 0
                type: integer
              write_timeout:
                minimum: 0
                type: integer
            type: object
          route:
            properties:
              headers:
                additionalProperties: true
                type: object
              https_redirect_status_code:
                type: integer
              methods:
                items:
                  type: string
                type: array
              preserve_host:
                type: boolean
              protocols:
                items:
                  enum:
                  - http
                  - https
                  - grpc
                  - grpcs
                  type: string
                type: array
              regex_priority:
                type: integer
              strip_path:
                type: boolean
          upstream:
            properties:
              algorithm:
                enum:
                - round-robin
                - consistent-hashing
                - least-connections
                type: string
              hash_fallback:
                type: string
              hash_fallback_header:
                type: string
              hash_on:
                type: string
              hash_on_cookie:
                type: string
              hash_on_cookie_path:
                type: string
              hash_on_header:
                type: string
              healthchecks:
                properties:
                  active:
                    properties:
                      concurrency:
                        minimum: 1
                        type: integer
                      healthy:
                        properties:
                          http_statuses:
                            items:
                              type: integer
                            type: array
                          interval:
                            minimum: 0
                            type: integer
                          successes:
                            minimum: 0
                            type: integer
                        type: object
                      http_path:
                        pattern: ^/.*$
                        type: string
                      timeout:
                        minimum: 0
                        type: integer
                      unhealthy:
                        properties:
                          http_failures:
                            minimum: 0
                            type: integer
                          http_statuses:
                            items:
                              type: integer
                            type: array
                          interval:
                            minimum: 0
                            type: integer
                          tcp_failures:
                            minimum: 0
                            type: integer
                          timeout:
                            minimum: 0
                            type: integer
                        type: object
                    type: object
                  passive:
                    properties:
                      healthy:
                        properties:
                          http_statuses:
                            items:
                              type: integer
                            type: array
                          interval:
                            minimum: 0
                            type: integer
                          successes:
                            minimum: 0
                            type: integer
                        type: object
                      unhealthy:
                        properties:
                          http_failures:
                            minimum: 0
                            type: integer
                          http_statuses:
                            items:
                              type: integer
                            type: array
                          interval:
                            minimum: 0
                            type: integer
                          tcp_failures:
                            minimum: 0
                            type: integer
                          timeout:
                            minimum: 0
                            type: integer
                        type: object
                    type: object
                type: object
              slots:
                minimum: 10
                type: integer
            type: object
    version: v1


- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: kongplugins.configuration.konghq.com
    labels:
      config: ingress-kong
  spec:
    additionalPrinterColumns:
    - JSONPath: .plugin
      description: Name of the plugin
      name: Plugin-Type
      type: string
    - JSONPath: .metadata.creationTimestamp
      description: Age
      name: Age
      type: date
    - JSONPath: .disabled
      description: Indicates if the plugin is disabled
      name: Disabled
      priority: 1
      type: boolean
    - JSONPath: .config
      description: Configuration of the plugin
      name: Config
      priority: 1
      type: string
    group: configuration.konghq.com
    names:
      kind: KongPlugin
      plural: kongplugins
      shortNames:
      - kp
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          config:
            type: object
          disabled:
            type: boolean
          plugin:
            type: string
          protocols:
            items:
              enum:
              - http
              - https
              - tcp
              - tls
              type: string
            type: array
          run_on:
            enum:
            - first
            - second
            - all
            type: string
        required:
        - plugin
    version: v1


- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: kong-ingress-clusterrole
    labels:
      config: ingress-kong
  rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    - nodes
    - pods
    - secrets
    verbs:
    - list
    - watch
    - get
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - networking.k8s.io
    - extensions
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
  - apiGroups:
    - networking.k8s.io
    - extensions
    resources:
    - ingresses/status
    verbs:
    - update
  - apiGroups:
    - configuration.konghq.com
    resources:
    - kongplugins
    - kongcredentials
    - kongconsumers
    - kongingresses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - update
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create


- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: kong-ingress-crd-edit
    labels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
      config: ingress-kong
  rules:
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongconsumers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongcredentials"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongplugins"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]


- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: kong-ingress-crd-view
    labels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
      config: ingress-kong
  rules:
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongconsumers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongcredentials"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongplugins"]
    verbs: ["get", "list", "watch"]
