apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kong-ingress-clusterrole-nisa-binding
